name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            output_name: gopress-linux
            install_cmd: sudo apt-get update && sudo apt-get install -y libheif-dev
          - os: windows-latest
            goos: windows
            goarch: amd64
            output_name: gopress.exe
            install_cmd: echo "No extra deps for Windows"
          - os: macos-14 # Apple Silicon (M1) runner
            goos: darwin
            goarch: arm64
            output_name: gopress-mac
            install_cmd: brew install libheif

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install Dependencies
        shell: bash
        run: ${{ matrix.install_cmd }}

      - name: Build
        shell: bash
        env:
          CGO_ENABLED: 1
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags "-s -w -X 'github.com/Pepegakac123/gopress/internal/version.CurrentVersion=${{ github.ref_name }}'" -o ${{ matrix.output_name }} ./cmd/gopress

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}
          path: ${{ matrix.output_name }}

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-linux
          path: artifacts

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-windows
          path: artifacts

      - name: Download Mac Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries-darwin
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: artifacts/*
          generate_release_notes: true
